---
name: Channels DVR Server
version: "1.0.0"
slug: channels-dvr
description: Manage and record live TV with Channels DVR Server
url: https://github.com/mekenthompson/hass-addon-channels-dvr
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
webui: http://[HOST]:8089
ports:
  8089/tcp: 8089
ports_description:
  8089/tcp: Web interface and API
map:
  - share:rw
  - media:rw
image: "fancybits/channels-dvr:latest"
hassio_api: true
backup: hot
schema: {}
