---
name: Channels DVR Server
version: 1.0.0
slug: channels-dvr
description: Manage and record live TV with Channels DVR Server
url: https://github.com/mekenthompson/hass-addon-channels-dvr
webui: http://[HOST]:8089
startup: services
arch:
  - aarch64
  - amd64
  - armv7
init: false
backup: hot
ports:
  8089/tcp: 8089
ports_description:
  8089/tcp: Web interface and API
hassio_api: true
map:
  - share:rw
  - media:rw
schema: {}
