---
name: Channels DVR Server
version: "1.0.3"
slug: channels-dvr
description: Manage and record live TV with Channels DVR Server
url: https://github.com/mekenthompson/hass-addon-channels-dvr/tree/main/channels-dvr
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
host_network: true
webui: http://[HOST]:8089
map:
  - share:rw
  - media:rw
hassio_api: true
schema: false
options: {}

